-- Initial chat persistence schema for session/message/tool logging.
-- Designed for Supabase Postgres with RLS by authenticated user.

create table if not exists public.chat_sessions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    mode text not null,
    title text,
    started_at timestamptz not null,
    ended_at timestamptz,
    metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_chat_sessions_user_started_at
    on public.chat_sessions (user_id, started_at desc);

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    session_id bigint not null references public.chat_sessions (id) on delete cascade,
    role text not null check (role in ('user', 'assistant', 'system', 'tool')),
    content text not null,
    tool_calls jsonb,
    estimated_tokens integer,
    estimated_cost numeric(12, 6),
    started_at timestamptz not null
);

create index if not exists idx_chat_messages_session_id
    on public.chat_messages (session_id);

create table if not exists public.tool_calls (
    id bigint generated by default as identity primary key,
    message_id bigint not null references public.chat_messages (id) on delete cascade,
    tool_name text not null,
    status text not null check (status in ('pending', 'ok', 'error')),
    input_args jsonb,
    output_result jsonb,
    error_message text,
    latency_ms integer,
    created_at timestamptz not null default now()
);

create index if not exists idx_tool_calls_message_id
    on public.tool_calls (message_id);

-- Enable row-level security.
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.tool_calls enable row level security;

-- Sessions policy: users can only access their own sessions.
drop policy if exists chat_sessions_owner_rw on public.chat_sessions;
create policy chat_sessions_owner_rw
    on public.chat_sessions
    for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- Messages policy: users can only access messages from their own sessions.
drop policy if exists chat_messages_owner_rw on public.chat_messages;
create policy chat_messages_owner_rw
    on public.chat_messages
    for all
    using (
        exists (
            select 1
            from public.chat_sessions s
            where s.id = chat_messages.session_id
              and s.user_id = auth.uid()
        )
    )
    with check (
        exists (
            select 1
            from public.chat_sessions s
            where s.id = chat_messages.session_id
              and s.user_id = auth.uid()
        )
    );

-- Tool calls policy: users can only access tool calls linked to their own sessions/messages.
drop policy if exists tool_calls_owner_rw on public.tool_calls;
create policy tool_calls_owner_rw
    on public.tool_calls
    for all
    using (
        exists (
            select 1
            from public.chat_messages m
            join public.chat_sessions s on s.id = m.session_id
            where m.id = tool_calls.message_id
              and s.user_id = auth.uid()
        )
    )
    with check (
        exists (
            select 1
            from public.chat_messages m
            join public.chat_sessions s on s.id = m.session_id
            where m.id = tool_calls.message_id
              and s.user_id = auth.uid()
        )
    );

-- RPC function wrappers so app can use RPC calls instead of raw inserts.
create or replace function public.create_chat_session(
    p_user_id uuid,
    p_mode text,
    p_title text,
    p_started_at timestamptz,
    p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    new_id bigint;
begin
    insert into public.chat_sessions (user_id, mode, title, started_at, metadata)
    values (p_user_id, p_mode, p_title, p_started_at, coalesce(p_metadata, '{}'::jsonb))
    returning id into new_id;

    return new_id;
end;
$$;

create or replace function public.complete_chat_session(
    p_session_id bigint,
    p_ended_at timestamptz
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
    update public.chat_sessions
    set ended_at = p_ended_at
    where id = p_session_id;
end;
$$;

create or replace function public.create_chat_message(
    p_session_id bigint,
    p_role text,
    p_content text,
    p_tool_calls jsonb default null,
    p_estimated_tokens integer default null,
    p_estimated_cost numeric default null,
    p_started_at timestamptz default now()
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    new_id bigint;
begin
    insert into public.chat_messages (
        session_id,
        role,
        content,
        tool_calls,
        estimated_tokens,
        estimated_cost,
        started_at
    )
    values (
        p_session_id,
        p_role,
        p_content,
        p_tool_calls,
        p_estimated_tokens,
        p_estimated_cost,
        p_started_at
    )
    returning id into new_id;

    return new_id;
end;
$$;

create or replace function public.create_tool_call(
    p_message_id bigint,
    p_tool_name text,
    p_status text,
    p_input_args jsonb default null,
    p_output_result jsonb default null,
    p_error_message text default null,
    p_latency_ms integer default null
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    new_id bigint;
begin
    insert into public.tool_calls (
        message_id,
        tool_name,
        status,
        input_args,
        output_result,
        error_message,
        latency_ms
    )
    values (
        p_message_id,
        p_tool_name,
        p_status,
        p_input_args,
        p_output_result,
        p_error_message,
        p_latency_ms
    )
    returning id into new_id;

    return new_id;
end;
$$;
